---
- ansible.builtin.import_tasks: tor_repo.yml

- name: Install Tor packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - deb.torproject.org-keyring
    - tor
    - tor-geoipdb
    - nyx
    - unbound

- name: Ensure Tor config directory exists
  ansible.builtin.file:
    path: "{{ tor_config_dir }}"
    state: directory
    owner: root
    group: "{{ tor_user }}"
    mode: 0755

- name: Install torrc configuration file
  ansible.builtin.template:
    src: torrc.j2
    dest: "/etc/tor/torrc"
    owner: root
    group: "{{ tor_user }}"
    mode: 0644
  notify: Restart tor

- name: Install Tor exit notice
  ansible.builtin.template:
    src: tor_exit_notice.html.j2
    dest: "/etc/tor/tor-exit-notice.html"
    owner: root
    group: "{{ tor_user }}"
    mode: 0644
  when:
    - tor_exit_notice_enabled | bool
  notify: Restart tor

- name: Enable IPv4 packet forwarding in sysctl.conf
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    state: present
    reload: yes

- name: Start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld.service
    enabled: yes
    state: started
    masked: no
  register: firewalld_service
  when:
    - tor_firewalld_config_enabled | bool

- name: Firewalld Tor Exit Notice rule
  ansible.posix.firewalld:
    port: "{{ tor_dirport }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  notify: Restart firewalld
  when:
    - firewalld_service is not skipped
    - tor_exit_notice_enabled | bool
    - tor_firewalld_config_enabled | bool

- name: Firewalld Tor Relay rule
  ansible.posix.firewalld:
    port: "{{ tor_orport }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  notify: Restart firewalld
  when:
    - firewalld_service is not skipped
    - tor_firewalld_config_enabled | bool

- name: Start and enable tor
  ansible.builtin.systemd:
    name: tor@default.service
    enabled: yes
    state: started
    masked: no
