---
- name: Tor Relay - Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- ansible.builtin.import_tasks: tor_repo.yml
- ansible.builtin.import_tasks: firewall.yml
  when:
    - tor_firewalld_config_enabled | bool

- name: Tor Relay - Install Tor packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - deb.torproject.org-keyring
    - tor
    - tor-geoipdb
    - nyx
    - unbound

- name: Tor Relay - Ensure Tor config directory exists
  ansible.builtin.file:
    path: "{{ tor_config_dir }}"
    state: directory
    owner: root
    group: "{{ tor_user }}"
    mode: 0755

- name: Tor Relay - Install torrc configuration file
  ansible.builtin.template:
    src: torrc.j2
    dest: "/etc/tor/torrc"
    owner: root
    group: "{{ tor_user }}"
    mode: 0644
  notify: Restart tor

- name: Tor Relay - Install Tor exit notice
  ansible.builtin.template:
    src: tor_exit_notice.html.j2
    dest: "/etc/tor/tor-exit-notice.html"
    owner: root
    group: "{{ tor_user }}"
    mode: 0644
  when:
    - tor_exit_notice_enabled | bool
  notify: Restart tor

- name: Tor Relay - Enable IPv4 packet forwarding in sysctl.conf
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    state: present
    reload: yes

- name: Tor Relay - Start and enable tor
  ansible.builtin.systemd:
    name: tor@default.service
    enabled: yes
    state: started
    masked: no
